# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OpenDataHub
email: opendatahub@redhat.com
description: >
  OpenDataHub
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://opendatahub.io" # the base hostname & protocol for your site
repo: https://github.com/opendatahub-io
email_list: https://lists.opendatahub.io/admin/lists/

# Build settings
lsi: false
safe: true
incremental: false
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
gist:
  noscript: false
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
    - imagesdir=images


permalink: /news/:year-:month-:day/:title:output_ext

plugins:
- jekyll-feed

include:
  - _next
  - _app
  - _buildManifest.js
  - _ssgManifest.js

exclude:
  - design
  - "README.md"
  - .idea
