:_module-type: PROCEDURE

[id="deleting-a-data-science-project_{context}"]
= Deleting a data science project

[role='_abstract']
You can delete data science projects so that they do not appear on the OpenShift Data Science *Data science projects* page when you no longer want to use them.

.Prerequisites
* You have logged in to Red Hat OpenShift Data Science.
* If you are using specialized OpenShift Data Science groups, you are part of the user group or admin group (for example, `rhods-users`) in OpenShift.
* You have created a data science project.

.Procedure
. From the OpenShift Data Science dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click the action menu (*&#8942;*) beside the project that you want to delete and click *Delete project*.
+
The *Delete project* dialog opens.
. Enter the project's name in the text field to confirm that you intend to delete it.
. Click *Delete project*.

.Verification
* The data science project that you deleted is no longer displayed on the *Data science projects* page.
* Deleting a data science project deletes any associated workbenches, cluster storage, and data connections. This data is permanently deleted and is not recoverable.

//[role='_additional-resources']
//.Additional resources
